### ISSUE TITLE
Port status on Load Configuration completion

### ISSUE THREAD

**Issue by AlexOQ** [QualiSystems/Ixia-IxNetworkController-Shell#4]
After Load Configuration has completed, the output states "$config_file$ loaded, ports reserved".
Would like to have the actual port status in addition to the output.
Example: "$config_file$ loaded, ports reserved. Port 1 up, Port 2 down."

**Comment by GalcQuali** [comment]
Hi Alex,

We are not showing or handling port status in our shells.

Thanks,
Gal.
